title: Luís Marques
email: euluismarques@gmail.com
description: >- 
  I'm a software developer specializing in building and 
  designing exceptional digital experiences.
keywords: >-
  luís,marques,luís marques,luis,luis marques,luismarques,software developer,software dev,
  software enginner,software dev,lead software dev,lead software developer,lead software engineer,
  senior software dev,senior software developer,senior software engineer,junior software dev,
  junior software developer,junior software engineer,frontend software dev,frontend software developer,
  frontend software engineer,fullstack software dev,fullstack software developer,fullstack software engineer,
  full stack software dev,full stack software developer,full stack software engineer,full-stack software dev,
  full-stack software developer,full-stack software engineer, ux,ui,ux/ui,ux ui,ux designer,ux ui designer,
  ux/ui designer,ux ui designer,Javascript,html,html5,pug,css,css3,sass,less,php,C,C++,C#,R,Python,Meteor,
  meteorjs,vue,vuejs,react,blaze,handlebars,jquery,git,bash,mongodb,mongo,sql,mysql,meteor up,meteor-up,
  meteorup,azure,aws,brainanswer,gametrade,golens,vectis,routrip,eyesee,giftlist,sms server,paperpile,ecovig,
  e-covig,speaker,explorer,tracher,artist,startups,workshops
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luismarques.io"
twitter_username: luismarques_io
github_username: luismarques-io
linkedin_username: luismarques-io

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
