title: Luís Marques - AI Solutions Architect
email: euluismarques@gmail.com
description: >-
    AI Solutions Architect at SAP BTP AI CoE. I design safe, scalable enterprise AI—agents, RAG, knowledge graphs, and reusable architectures on SAP BTP.
keywords: >-
    luís,marques,luís marques,luis,luis marques,luismarques,ai solutions architect,enterprise ai,sap btp,sap business ai,
    langgraph,langchain,rag,knowledge graphs,generative ai,architecture,python,typescript
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luismarques.io"
twitter_username: luismarques_io
github_username: luismarques-io
linkedin_username: luismarques-io

# Build settings
#theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: compressed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
